# Generated by Django 4.2.1 on 2024-02-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Без названия", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Фото",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("size", models.TextField(blank=True, verbose_name="Размер")),
                ("content", models.TextField(blank=True, verbose_name="Описание")),
                ("material", models.TextField(blank=True, verbose_name="Материал")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Главное фото на главной странице",
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cats",
                        to="shopping_site.category",
                        verbose_name="Категории",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="photos",
                        to="shopping_site.images",
                        verbose_name="Фотографии в карточке товара",
                    ),
                ),
            ],
        ),
    ]
