# Generated by Django 4.2.1 on 2024-03-02 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_site", "0006_alter_comments_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
